### ISSUE TITLE
Trim encounters out of bounds subsequence when splitting

### ISSUE THREAD

**Issue by hwalinga** [jteutenberg/downpore#4]
Hello, I encountered a small problem (albeit fatal) when trimming my fastq files. The problem is obvious, but it is not that clear how it exactly arises when I glanced over the code. Here the technical details:

---

Downpore compiled from source

go1.12.5 linux/amd64

Ubuntu 18.04.2 LTS

---

Running command:

```bash
downpore trim -n 1 -v 2 -i nanofilt_fastq/S31.filt.fastq -f $DOWNPORE/data/adapters_front.fasta -b $DOWNPORE/data/adapters_back.fasta > trimmed_fastq/S31.trimmed.fastq 
```

Gave error: `panic: runtime error: slice bounds out of range` 

https://termbin.com/h7007

Verbose output is clear: 

2019/06/06 22:33:45 Splitting read  92817  into: 0 - 6016 and 6244 - 6157.

6244 - 6157 is an invalid range (start exceeds the length). 

---

So, a possible solution is to just discard the sequence with the invalid range, but there might be a deeper underlying problem that causes the invalid range to arise in the first place, but that is more up to you to decide what to do with it. 

If you want to, I can write the naive solution (just discarding invalid ranges) and make a pull request.

**Comment by jteutenberg** [comment]
Thanks for the report. I'd like to track down what happened here if possible. Are you able to send me a copy of the read that this happened on?
I believe the restriction for internal adapters to not appear near read edges was not applied properly in this case. Edit: actually I think I can see a case where this would happen, when there has been a large trim due to an adapter at the front and an internal adapter near the end. I will commit a patch tomorrow to address this and hopefully it fixes the bug you ran in to.

**Comment by hwalinga** [comment]
Well, here you have the read that causes this problem: 

https://termbin.com/siqn

However, it only produces this problem in the context of the other reads, not on its own.

**Comment by jteutenberg** [comment]
Thanks. The example is consistent with the bug I identified. I've committed a fix which hopefully handles the problem you encountered too.

**Comment by hwalinga** [comment]
Your patch solves the problem I encountered with the specific case I send you. (Thanks for that.) However, I still encounter the same problem (start is out of bounds) with other cases. Probably some related edge cases that are still left.

Here I extracted some of these, hope you can take a look:

https://termbin.com/3my7g

NB. This file itself will generate the error on the current patched version, so you can use it as a test case for your debugging.

**Comment by jteutenberg** [comment]
Great, that's a really useful example. The problem occurs when paired front and back adapters are in a chimeric read (so it gets split by both the end adapter of the first read and the start adapter of the second) and at least one of the two reads is right at the edge of the minimum length to be kept.

I have added a test so that if the second split reduces a sequence to below the minimum length it gets ignored downstream. Let me know you encounter any other problems on your data.
